# Generated by Django 2.1.7 on 2019-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190321_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['url']},
        ),
        migrations.RemoveField(
            model_name='url',
            name='category',
        ),
        migrations.RemoveField(
            model_name='url',
            name='site_text',
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SiteText',
        ),
    ]
