# Generated by Django 2.1.7 on 2019-03-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190321_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['url_path']},
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='url_path',
        ),
    ]
