# Generated by Django 2.1.7 on 2019-03-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190322_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='description',
        ),
    ]
