# Generated by Django 2.1.7 on 2019-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_url_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='UrlText',
        ),
    ]
